### ISSUE TITLE
BUG: No link to release banner in Dutch

### ISSUE THREAD

**Issue by larssondenise** [cherrytwist/Coordination#1017]
**Describe the bug**
The banner that highlights whether there is a new release, doesn't have a link in the Dutch translation

**To Reproduce**
1. Go to 'home page'
2. Set language to Dutch
3. See error

**Expected behavior**
'Meer lezen over deze veranderingen?' to be clickable

**Screenshots**
![image.png](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/022022ea-f66c-4a38-bf85-8483314abb8f)

**Comment by SimoneZaza** [comment]
this was addressed in this sprint, right?
