### ISSUE TITLE
Spike: prototype usage of hocus pocus for real time collaboration of markdown

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1072]
## Description
As a developer I want to understand the implications of working with hocuspocus

## Acceptance criteria

- [ ] Evaluate usage of hocuspocus in a local development setup that is able to have two users working on markdown in two separate browsers
- [ ] If possible see if we can host a markdown editing component in our client that can connect to the hocuspocus service
- [ ] Gather findings in a markdown file / on whiteboard

Timebox: 1 day? 

## Additional Context
Screen shots / UX designs / data that are relevant.

**Comment by ccanos** [comment]
https://hackmd.io/eVSTnCu_QpmJDRlyd6QnQQ
https://github.com/alkem-io/client-web/pull/4171
