### ISSUE TITLE
Database migration squish

### ISSUE THREAD

**Issue by hero101** [cherrytwist/Coordination#1118]
## Description
Brief summary of what this Epic is, whether it's a larger project, goal, or user story. Describe the job to be done, which persona this Epic is mainly for, or if more multiple, break it down by user and job story.

## Initiative / goal
Increase the productivity of the team and reduce the complexity created by the large number of migrations.

### Hypothesis
Recreating a database from scratch requires running around 130 migrations (currently) which depending on the environment can be very slow. This downtime is very unproductive and discouraging if you want to test a simple bug or you have a data integrity issue.
Migrating data is multiple times slower and some migrations tend to migrate a lot of data.
The opportunity here is to reduce the downtime of getting your schema ready and reduce the complexity of all the migrations you have to run to b e up-to-date.

**Comment by techsmyth** [comment]
Moved as part of the Data Integrity v2 epic

**Comment by techsmyth** [comment]
Merged into server alkem-io/server#2329
