### ISSUE TITLE
Create on Create, not on Save

### ISSUE THREAD

**Issue by SimoneZaza** [cherrytwist/Coordination#1153]
## Description
Currently, when a user tries to create something (eg a post, or a Challenge, or even an innovation hub), this only gets created **after** clicking on the save button. This causes for issues when trying to attach files or images to it. In for example innovation hubs, images that are added to the description field are stored in the platform storage, and the same for challenges get saved in the space storage.
During the bug squashing session it was suggested to actually create something (temporarily?) when the create button is clicked and the form is opened, so before anything has been specified, like it's being done with the call for links when a user adds a link. Another approach would be to move all items to the right entity after it has been created.

## Initiative / goal
Describe how this Epic impacts an initiative the business is working on.

### Hypothesis
What is your hypothesis on the success of this Epic? Describe how success will be measured and what leading indicators the team will have to know if success has been hit.

## Acceptance criteria and must have scope
Define what is a must-have for launch and in-scope. Keep this section fluid and dynamic until you lock-in priority during planning.

## Stakeholders
Describe who needs to be kept up-to-date about this Epic, included in discussions, or updated along the way. Stakeholders can be both in Product/Engineering, as well as other teams like Customer Success who might want to keep customers updated on the Epic project.

## Timeline
What's the timeline for this Epic, what resources are needed, and what might potentially block this from hitting the projected end date.

## Design
Figma file:
_Comments are highly appreciated. When commenting in Figma, please also leave a note in the comments box below this issue to notify us_

**Comment by SimoneZaza** [comment]
@techsmyth this is also a big thing with regards to the storage buckets. Currently all uploaded items that are inserted when creating a challenge or callout (eg images in the description) are added to the space bucket instead of the bucket of the challenge or callout itself. This is quite confusing..
Oh I now see that I already added that in the description, never mind..

**Comment by techsmyth** [comment]
@SimoneZaza I think this epic can be closed with the temporary storage work?

**Comment by SimoneZaza** [comment]
@techsmyth yes, I moved the issue about the storage buckets for images in md fields and whiteboards during the create proves to the Using temporary storage epic and will close this one.
