### ISSUE TITLE
After verifying email - redirect to sign in

### ISSUE THREAD

**Issue by SimoneZaza** [cherrytwist/Coordination#1236]
## Description
As a user going through the -quite long-  process of signing up, I want to be signed in at the last step! If this is really not possible, the last screen should at least redirect to the sign in page

## Acceptance criteria

- [ ] Bring user to sign in page after successfull email verification
- [ ] …

## Additional Context

Consider having a look at Kratos config

User login flow: https://alkem.io/building-alkemio-org/challenges/improvingtheusere-6400/collaboration/userflowsaftersig-6195

**Comment by valentinyanakiev** [comment]
@SimoneZaza ory kratos 1.1.0 is out as of yesterday. Maybe we check what's possible with the new version before we jump in on that? Maybe it will be possible to keep the user signed in, at least in some scenarios - worth checking it...

**Comment by SimoneZaza** [comment]
@valentinyanakiev That would be amazing! Any idea when there is time to investigate this?

**Comment by valentinyanakiev** [comment]
@SimoneZaza let's plan it in, it should be fairly easy to follow up on this one, and it should be doable according the documentation

**Comment by SimoneZaza** [comment]
@valentinyanakiev does this mean that also after this Kratos update we still cannot automatically sign the users in after the verification flow? (#765, https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/infrastructure-operations/765) 😥
I've tagged it for next sprint.
