### ISSUE TITLE
Space Defaults to reflect what most communities currently need

### ISSUE THREAD

**Issue by SimoneZaza** [cherrytwist/Coordination#1268]
## Description
As an admin, I want the settings, callouts, and other things that are there by default at the creation of a new Journey, to be relevant and informative. As a S&D team member, I want to have to change and explain as little as possible to new admins. Currently, many of the defaults, like the default innovation flow and default callouts, are irrelevant or even confusing. Also some of the default settings are immediately changed once a new space or challenge is created.

## Goal
Space Defaults to reflect what most communities currently need

## Hypothesis
When this epic is finished, it should be less work to set up a new Space or Challenge. Also, the S&D team should need less time to prepare for the onboarding of new communities.

## Must have scope
- Settings
- Innovation flow
- Templates
- Callouts

## Stakeholders
Customer Success and Product

**Comment by techsmyth** [comment]
@SimoneZaza can you please split what is left of this out to a new epic and close this one? If any of the remaining issues should happen near term then good to get them planned in. Just good to have the epic closable...

**Comment by SimoneZaza** [comment]
@techsmyth only 1 issue left, I'm just waiting for the Subspaces to be finalized so I can directly put it in the right place.

**Comment by techsmyth** [comment]
Moved the last issue to the epic on findings, so it will be done - just want to get a clearer view on open epics...
