### ISSUE TITLE
Space AI service - EU LLM

### ISSUE THREAD

**Issue by bobbykolev** [cherrytwist/Coordination#1336]
## Description
We need alternatives to the LLM, ideally open source and cost-effective.

## Must have scope
- [ ] An EU-based LLM, running with similar responses to the OpenAI's one.
- [ ] Revise the embeddings model (detach from OpenAI).

**Additional info:**
LLMs to test:
- Mistral (open and closed) 
- Groq (LPU)

**Unknown** - LLM response quality?
**Limitations** - language support?

https://docs.mistral.ai/getting-started/models/

**Comment by SimoneZaza** [comment]
duplicate #1332
