### ISSUE TITLE
VC: Usability, creation flow

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1348]
## Description
_Brief summary of what this Epic is, whether it's a larger project, goal, or user story. Describe the job to be done, which persona this Epic is mainly for, or if more multiple, break it down by user and job story._

## Goal
_Describe how this Epic impacts an initiative the business is working on._

## Hypothesis
_What is your hypothesis on the success of this Epic? Describe how success will be measured and what leading indicators the team will have to know if success has been hit._

## Must have scope

- [ ] Polishing of the overall user experience
- [ ]  If a VC is inactive there should be an indication (visual, automatic reply etc)
- [ ]  

## Stakeholders
_Describe who needs to be kept up-to-date about this Epic, included in discussions, or updated along the way. Stakeholders can be both in Product/Engineering, as well as other teams like Customer Success who might want to keep customers updated on the Epic project._

**Comment by bobbykolev** [comment]
With the new creation flow, I think we shouldn't set the VC as lead of the BoK. It was a workaround for having a quick link to the profile. Now the VCs are visible as part of the communities.
