### ISSUE TITLE
Education NL: using existing logins

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#1381]
## Description
Allowing identities already in use within the education market in NL to be used to login to Alkemio. 

## Goal
Adoption in the education market in NL

## Hypothesis
Making it easy for existing users in education to authenticate + work with Alkemio would make adoption of Alkemio much easier.

## Must have scope
- [ ] Understand the implications to be able to leverage surfcontext as a login mechanism

## Stakeholders
Education market customers

## Context
The key educatation digital infrastructure cooperative in NL is surf.nl. 
https://www.surf.nl/en/services/surfconext

## Design
Figma file:
_Comments are highly appreciated. When commenting in Figma, please also leave a note in the comments box below this issue to notify us_

**Comment by SimoneZaza** [comment]
merging this one with #1452
