### ISSUE TITLE
Make sidebar collapsed by default

### ISSUE THREAD

**Issue by keyboardguy25** [cherrytwist/Coordination#1384]
## Description
As a user
I want the sidebar in a subspace to be collapsed by default
So that my digital workspace isn't cluttered / I'm not overwhelmed by the amount of information on my screen at once

## Acceptance criteria

- [ ] Sidebar in a subspace to be collapsed by default

## Additional Context

<img width="1902" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM0R2QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7a2f41a68033c08b60b27402c15549995c1acc80/Screenshot%202024-07-18%20at%2016.25.19.png" alt="Screenshot 2024-07-18 at 16.25.19.png" />

**Comment by SimoneZaza** [comment]
@keyboardguy25 thanks for raising this issue. I fully understand, but at the same time, I do think it's important for new users to see the panel to understand where they are. So instead, I suggest that the browser remembers whether you had your panel expanded or collapsed the last time you visited a subspace (that was still open from the change to subspaces, #6076). I'll close this one and add #6076 to the list of summer improvements.
