### ISSUE TITLE
S&D: Review & remove redundant VCs

### ISSUE THREAD

**Issue by valentinyanakiev** [cherrytwist/Coordination#1448]
## Description
As an Alkemio Service Manager
I would like not to have redundant data in the database
so that queries do not return 'experimental' data.

## Acceptance criteria

- [ ] There are no redundant VCs in the database

## Additional Context
Run the following query:

```gql
query {
  virtualContributors{
    id
    nameID
    aiPersona {
      bodyOfKnowledge 
      bodyOfKnowledgeID
      bodyOfKnowledgeType
    }
  }
}
```

there are a bunch of VCs with nameID e.g. `v-p-e380c615-6906-4e24-9a`.
Review which one of those are needed and which ones aren't

The VCs can be accessed at https://acc-alkem.io/vc/[VC_nameID]/settings/settings

**Comment by DonnaDuiker** [comment]
Overview doc: https://stichtingcherrytwist-my.sharepoint.com/:x:/g/personal/donna_alkem_io/EcsMWOuo7-BLq2T9y0TXRkQBWoGoBnjaK7qUJqyj-YH0IQ?e=mQaheB

**Comment by DonnaDuiker** [comment]
@valentinyanakiev There is some VC's that I created in the beginning that I will remove, however I think you are mostly referring to the VC's in this screenshot:

 ![Image](https://github.com/user-attachments/assets/f9489624-bf51-4379-98c9-0eaed8a89e07)

I think most of them are not redundant. Is there a problem with the nameID being a code, does that need to be changed?
