### ISSUE TITLE
Enhance ecoverse navigator

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#193]
About page:
https://xd.adobe.com/view/eb6c3fc0-8873-44b6-9f63-01b020d4a8dc-be3f/screen/d23e517b-1eba-4559-9f45-2ad09e520f4f/?fullscreen

Latest design:
https://xd.adobe.com/view/eb6c3fc0-8873-44b6-9f63-01b020d4a8dc-be3f/screen/ded32523-f068-455b-add8-530eda64f68a/?fullscreen

**Comment by oldhoyte** [comment]
@larssondenise
