### ISSUE TITLE
Select open source license 

### ISSUE THREAD

**Issue by wordsmyth73** [cherrytwist/Coordination#3]

**Comment by positivedefinite** [comment]
AGPL? ;) "Contagious FOSS innovation platform"

**Comment by wordsmyth73** [comment]
Thoughts on EU-PL? Also important that it can be adopted by corporates /
public entities - and there AGPL has challenges

**Comment by wordsmyth73** [comment]
Choice is for EU-PL

Rational:

Considerations
- Encourage uptake by established organisations (corporates, gov) as well as newer organisations
- Ensure usage of the platform is “safe” i.e. implications are understood
- Ensure platform can be integrated with solutions under different licenses.
- Especially as likely will need a lot of integrations need to ensure it is clear what interacting code licensed under other licences implies

Options considered:

GPL + variants:
- Can limit connections / usage
- Likely raises too many concerns with some of the target users / integrations

Apache
- Widely recognised
- Patent coverage is solid, including for defensive purposes

EU-PL
- Up and coming, recommended option
- Very clear guidance on integrations with other license types (i.e. analysis already done)
- Easier acceptance especially for public sector usage
- Clear jurisdiction / legal framing
- Also strong / clear patent guidelines / coverage
- Implications for usage outside of EU needs additional clarity
