### ISSUE TITLE
Multiple callouts

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#310]
## Description
Community admins want to gather knowledge and insights from the community to make progress. They can make callouts and decide whether they want the community to submit their knowledge and insights via cards, canvases, or comments.

The community can then submit their contribution via the chosen answer type.

### Hypothesis
By allowing a community admin to make multiple callouts, they can better engage their community. They can:
* (1) publish multiple callouts to gather wisdom about different issues that are important for that challenge at that point and 
* (2) choose the callout type according to what the most fitting way to receive answers from their community (see additional context for examples). 

## Acceptance criteria and must have scope
- [ ] Allow multiple callouts per community
- [ ] Support the following callout types: canvases, cards, discussion 

## Stakeholders
UWV for programme roll out beginning Sept

## Timeline
Mid Aug

## Additional context
https://hackmd.io/qCygguVSTgqIIvPu_jucZw 
For example:
![Schermafbeelding 2022-08-09 om 14.07.40.png](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/bd2b4c82-7366-4f32-8392-1d4a3fdd06a5)

## Design
Figma: https://www.figma.com/file/olZkcLJKpUYRMjakhfGpB8/Call-outs?node-id=0%3A1
We decided on using Callout (no call out or call-out)

**Comment by larssondenise** [comment]
@valentinyanakiev user story further defined!
