### ISSUE TITLE
Landing page login buttons incorrect navigation

### ISSUE THREAD

**Issue by hero101** [cherrytwist/Coordination#330]
## Steps to reproduce

- [ ] You are not authenticated
- [ ] Go to the landing page
- [ ] Press either of the buttons to login in order to view more info

## Expected results

- [ ] You are navigated to the login page

## The problem

- [ ] You are navigated to the 404 page

![image](https://user-images.githubusercontent.com/7901834/121514723-02700b80-c9f5-11eb-8f3f-be864a842de8.png)
![image](https://user-images.githubusercontent.com/7901834/121514743-09971980-c9f5-11eb-86aa-d594eeabcca8.png)

**Comment by techsmyth** [comment]
Issue moved to [cherrytwist/client-web #633](https://github.com/cherrytwist/client-web/issues/633) via [**ZenHub**](https://www.zenhub.com/)
