### ISSUE TITLE
Managing the groups of a community throws an exception

### ISSUE THREAD

**Issue by hero101** [cherrytwist/Coordination#339]
**Describe the bug**
Managing the groups of a community throws an exception

**To Reproduce**
1. Login as a role with edit privilages
2. Go to Admin section
3. Click on Ecoverses > Manage
4. Choose an ecoverse
5. Click on "Groups"
6. Choose a group

**Expected behavior**
The client application must not throw an exception.

**Screenshots**
![image](https://user-images.githubusercontent.com/7901834/123215261-e67a6880-d4d0-11eb-9137-e969caebde2b.png)
![image.png](https://images.zenhubusercontent.com/60af3d8c46d844c399496234/7a6d487a-205e-450e-ba9e-4f2a0d06535b)

**Comment by techsmyth** [comment]
Issue moved to [cherrytwist/client-web #673](https://github.com/cherrytwist/client-web/issues/673) via [**ZenHub**](https://www.zenhub.com/)
