### ISSUE TITLE
Dialog backdrop is not ontop of sidebar

### ISSUE THREAD

**Issue by hero101** [cherrytwist/Coordination#356]
1. Draw a popup dialog
2. Backdrop should be displayed over everything and on top of it - the dialog

![image.png](https://images.zenhubusercontent.com/60af3d8c46d844c399496234/035019bd-dc09-49c0-964c-ff8dc5b20a46)

**Comment by techsmyth** [comment]
Issue moved to [alkem-io/client-web #790](https://github.com/alkem-io/client-web/issues/790) via [**ZenHub**](https://www.zenhub.com/)
