### ISSUE TITLE
Accounts cleaned up on Azure

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#359]
## Description

As a CT Service Manager
I want to have only alkem.io accounts for the dev team access azure
so that there is no clutter and obsolete accounts with elevated privileges there.

## Acceptance criteria

- [x] Remove personal account access to Cherrytwist azure resources
- [x] Add operational access to Valentin, Neil, Rene for all resources with alkem.io accounts
- [x] Give access to the dev resources (dev, test, acc) to the dev team with their alkem.io accounts

**Comment by valentinyanakiev** [comment]
Created 4 Groups in AAD

- Alkemio Developers - the dev team. Contributor access up to Acc.
- Alkemio Admins - full administrative access (owner level) on k8s. Valentin / Neil / Rene
- Alkemio IT Admins - owner access to the DNS zones. Valentin / Neil / Rene.
- Alkemio Subscription Admins - Valentin / Neil (Rene wasn't there originally, so I didn't add him. Can be easily added if needed).

Neil is everywhere with the Neil_Admin account. I have removed access for my (valentin_yanakiev@yahoo.co.uk) personal account. I have access with valentin@alkem.io and only access with alkem.io is used. Also cleaned up some 'dead' accounts on subscription level.

Now providing access to the specific envs can be done by simply adding people to the group.

NB. This is not in terraform. Ideally should be done / linked there, but that won't be a quick fix. Let's first validate whether, security - wise, this makes sense.
