### ISSUE TITLE
'Base' and 'UpdateBase' entity have different names for 'id' field

### ISSUE THREAD

**Issue by hero101** [cherrytwist/Coordination#366]
**Is your feature request related to a problem? Please describe.**
`BaseAlkemioEntity` and `UpdateBaseAlkemioEntity` have different 'id' fields which requires field renaming in order to mutate entites in the client.
**Describe the solution you'd like**
Same name fields so that the entities are mutated easier, with less code

**Additional context**

![image.png](https://images.zenhubusercontent.com/60af3d8c46d844c399496234/159097c7-ebda-4502-b814-abcbc370f345)
![image.png](https://images.zenhubusercontent.com/60af3d8c46d844c399496234/45172a52-879d-4565-b6ee-631ccb3b85d8)

**Comment by techsmyth** [comment]
ah, interesting one - and a wider discussion...

we use "id" for everywhere where we are reading data from our api
we use "ID" for everywhere that we are providing input

we could standardise on using "id" everywhere but that is a fairly big change that would not bring I think that much benefit - but open to comments...

**Comment by techsmyth** [comment]
Actually this is more related to the fact that we use 'id' for the name of the column that is stored in typeORM
