### ISSUE TITLE
Integration of sign-up and application

### ISSUE THREAD

**Issue by FloriSpoelstra** [cherrytwist/Coordination#395]
From a user perspective I think it would be great if you can apply directly for an ecoverses/challenge/opportunity as part of the sign-up proces. Or we need to remind people somehow that they still have to apply for something to become part of a community. Because that is the actual problem: most people are not finding their way to the apply buttons (we have far more sign-ups than we have applications).

_Originally posted by @FloriSpoelstra in https://github.com/alkem-io/alkemio/discussions/382#discussioncomment-1081971_

**Comment by FloriSpoelstra** [comment]
I just found out I can create a new issue from a previous issue. I am marking the other one as answered. This part of the issue still remains: how to make it easier for people to find their way to the apply buttons. The integration of sign-up and application is just a suggestion. There might be other/better ways.

**Comment by FloriSpoelstra** [comment]
I have somehow posted this in the wrong section. @techsmyth can you help me move this to the discussions?

**Comment by techsmyth** [comment]
#florispoelstra afraid the easiest is just to create a new discussion  topic, copying over a link if you want to this issue...

**Comment by FloriSpoelstra** [comment]
Done! I will close this one now.
