### ISSUE TITLE
UX of Communications Page

### ISSUE THREAD

**Issue by Enderedne** [cherrytwist/Coordination#451]
## Description

As a user, I want to be able to find and consume information captured by a community in the form of updates/discussions.

## Acceptance criteria
- [x] Display the name of the community
- [ ] Add capability to go back to the hub/challenge/opportunity
- [x] Show community updates and specifics such as:
- - [x] When the update was posted
- - [x] The content of the update
- - [x] Who posted the update
- - [x] When was the update last edited
- [x] Updates can be an unlimited amount and are in chronological order (based on creation, not update)
- [x] Show discussions / thread with specifics such as:
- - [x] Users are able to browse threads
- - [x] There is a message that acts as a start of a discussion.
- - [x] Show the number of responses in a thread
- - [x] There could be an unlimited number of responses in a thread.
- [x] Allow users to start a discussion
- - [ ] Have predefined templates?
- - [x] Whether to expand - show in place or lead to a page?
During last discussion: 2 tabs
- - [x] Updates
- - [x] Discussions - which will contain the overview, discussion in detail and discussion initiation

## Additional Context

The information that each community update / discussion contains is:
- **TITLE (Essential)** - need to investigate solutions (technically)
- **Later update: STATE** - open / closed - need to investigate solutions (technically)
- **Later update: CATEGORIES** - ideas / q & a / e.g. - need to investigate solutions (technically)
- **timestamp** - when it was sent
- **update timestamp** - when it was updated
- **sender** - name + avatar
- **content** - supports markdown - which means that a certain point in time they might add tables / pictures e.g. found [here](https://mermaid-js.github.io/mermaid/#/)

While creating the design keep in mind the [Material concepts and the development library used](https://mui.com/)
Github discussions as reference

**Comment by Roseghost** [comment]
- Updates page (https://xd.adobe.com/view/145637b9-fc8a-4b2b-a818-36498066819c-4105/)
- Discussions (https://xd.adobe.com/view/9f5df785-4222-400e-9db0-3ab785964328-ca0e/)
- Discussion in Detail (https://xd.adobe.com/view/c4333267-959e-44b2-a6dc-98462394f4f2-9160/)
- Discussion Initiate (https://xd.adobe.com/view/4651e821-07ba-4ae0-9163-99fa2b0e9cde-1302/) 
- Community Panel Update (https://xd.adobe.com/view/665fce90-f549-4cef-a24f-6754f0a2ed28-330c/)

**Comment by KayleeS96** [comment]
We have updated all links mentioned by Rose above. Per discussion with Nikola we have made some changes to the discussions overview page. This now has a different display of the category icons and we have made a second version with the user avatars added. Link to the discussion overview pages (https://xd.adobe.com/view/9f5df785-4222-400e-9db0-3ab785964328-ca0e/)
