### ISSUE TITLE
LinkedIn Banner

### ISSUE THREAD

**Issue by Enderedne** [cherrytwist/Coordination#477]
## Acceptance criteria

- [ ] Ratio 1:4
- [ ] Alkemio Logo, Digicampus logo
- [ ] Visuals around Connecting across silos: aligning innovation efforts

**Comment by KayleeS96** [comment]
@techsmyth here's our idea for the banner, let us know if something needs to be adjusted.
![Banner_Neil.png](https://images.zenhubusercontent.com/612cb1848a783db262f19451/7f12099e-c365-4c5f-95b9-e2ed51ab440d)

**Comment by techsmyth** [comment]
Looks great, only request is to swamp Digicampus + Alkemio. 

One further thought: any way to "layer" the visual, so that Digicampus is "using" Alkemio?

**Comment by Roseghost** [comment]
![Banner Neil – 1.png](https://images.zenhubusercontent.com/612cb1604df0ebe2138b93c9/2892d77e-a623-4462-afb1-8834500f8af8)

New requested version

Alkemio logo has to be made smaller in the profile section to match the same height of Digicampus to look more fluent.

**Comment by techsmyth** [comment]
Thanks, looks great!

Think this visualization might be more widely applicable :)
