### ISSUE TITLE
UX: Preference Management

### ISSUE THREAD

**Issue by valentinyanakiev** [cherrytwist/Coordination#491]
## Description
As an Alkemio user
I want to see User Preferences grouped and visualized in a meaningful way.

## Acceptance criteria
- [x] Notifications settings tab to have two groups: one for notifications related to my usage, one for notifications related to my role as an admin

## Additional Context

Can be found in the original design that was approved at user management: 

https://xd.adobe.com/view/88438054-bf02-45f5-b978-874a8ab0e11d-dd10/screen/d5f03340-1a09-4046-acce-b2d639a83f47/

**Comment by Roseghost** [comment]
See additional context for design. Administration in different colour to show difference is optional.
