### ISSUE TITLE
Notifications on the client

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#493]
## Description
As a user I want to see the latest data and get notifications on the client

## Acceptance criteria

- [ ] Design for what data is sent via subscriptions vs polling updates
- [ ] Design for how notifications about new events are raised on the client e.g. popup on update, message center etc
...

## Additional Context
Currently there are two subscriptions for real time data:
- updates on a community where the currently authenticated user is a member
- messages to existing discussions on a community where the currently authenticated user is a member

Some example situations that are not covered now:
- New discussion is created
- Updates / discussion messages where a user is not a member of that community

The complexity arises from the fact that we currently trigger communication related events via the rooms on Matrix, which we then transform via the subscriptions.

**Comment by SimoneZaza** [comment]
@techsmyth I think this one is a bit outdated/redundant. Can you check+close?

**Comment by techsmyth** [comment]
Yes this can be closed...
