### ISSUE TITLE
UX: Newsletter format

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#494]
## Description
As a newsletter subscriber I want the format to align with the rest of the Alkemio branding

## Acceptance criteria

- [ ] Design for the newsletter layout / structure
- [ ] Align with the email format used for notifications

**Comment by Roseghost** [comment]
Hi Neil and Nikola, 

We need to know the following regarding the future content on this issue. 
- Will there be event mails? (such as christmas or an opening for something)
- Will there be a welcome mail? Such triggers as an option in mail services
- What will be the general content of a newsletter? 
	Suggestion : 
        - Events (coming 4 februari there's a get together here and there)
        - Announcements
        - Requests to action (sign up this, see our new feature)
        - Pictures (lookback on events or new products)
         - Anything else? 

We need these criterias else we are building a house without knowing the people that are going to live in it.

**Comment by techsmyth** [comment]
Newsletter contents:
- Introduction text 
- Highlight recent activity / blogposts
- Events
- Calls to action

**Comment by Roseghost** [comment]
![screencapture-mail-google-mail-u-0-2022-01-31-10_41_29.png](https://images.zenhubusercontent.com/612cb1604df0ebe2138b93c9/68dfbce9-1179-470b-8c0d-c14d484d9c82)

Picture for reference - See how banner has white logo and there for banner is easy switchable? this is great for events such as christmas or event related. for the rest the build up , first general information than blocks of other information, between social media to join and participate the community, underneath it small blocks with events coming up or new things to join and at last partners/sponsor and the ''contact us'' section.
