### ISSUE TITLE
UX: Banners are not used consistently

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#495]
**Describe the bug**
On a card for the Hub the banner is left aligned:
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/db4a8f1e-ff1f-4d67-8827-672e181a8534)

On the Hub dashboard the banner is centered:
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/e28bbe3a-5a86-4d29-ada9-b669eb1813b6)

It means that if the banner is not the exact width then it always shows up badly.

**To Reproduce**
View [The Hague hub ](https://hub.alkem.io/the-hague/dashboard) on prod

**Expected behavior**
Banners to be centered on the cards

**Comment by Comoque1** [comment]
Much better now.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/7ca1f3ce-2ff5-4fd1-a07c-4b1b9ca7c905)
