### ISSUE TITLE
Analysis of Hub hosting costs

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#502]
An an admin I want to know where our monthly charges are being incurred

## Acceptance criteria
- [ ] Review monthly bills for dec on AWS + Azure, and look at where the costs are going
- [ ] Suggestions for where / how to save costs. 

AWS for Dec:
[https://app.zenhub.com/files/266739765/d6160c0a-2f8b-46bb-9866-931d5b2b8cad/download](https://app.zenhub.com/files/266739765/d6160c0a-2f8b-46bb-9866-931d5b2b8cad/download)

Azure:
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/6f2bb3fd-01fc-4d6f-9c78-54f7025a1dc7)

AWS:
![image.png](https://images.zenhubusercontent.com/5f227562fdc101c42f08046f/491de02f-337b-4ec9-aba4-a635f0185e8d)

One question that springs to mind is why the AWS costs are so much higher than the Azure costs of approx 300 / month per env. On AWS we have dev, test, demo but that still should not be 1,600. What else is running on there?

**Comment by valentinyanakiev** [comment]
There are no unwanted tools / packages running that I found. The major difference is between the number of nodes and their class (which defines the price). AWS and Azure VM classes are not directly comparable.

The number of nodes is 11 T2.Large (AWS) vs 6 Standard D2_V2(Azure).
On-demand price is $0.0928 per hour for T2.Large and $0.114 for Standard D2_V2. 
On-demand **is the most expensive plan**. We can do massive savings (about 1/2 of the instance price) reserving it for 1 year and about 2/3s if we reserve them for 3 years.

Also, currently dev is overprovisioned with 2 instances - I will scale them down from 5 to 3, which will save us some costs.
