### ISSUE TITLE
UX: Canvas template for ecosystem value mapping

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#503]
## Description
As a user I want to be able to create an ecosystem value map

## Acceptance criteria

- [ ] New canvas template for ecosystem value mapping
-- Template: https://excalidraw.com/#json=L3lE366mbQe2S3tc3vlsb,mfa8pHac2AYmKVmvNO8HUw

Evgeni: please try uploading the canvas above onto dev...

## Additional Context

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/92b43465-e83a-4b8c-abcc-f9e1df6eb55b)

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/b635e89e-4649-49c2-849e-e42ab47c9be9)

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/89ef4191-8932-4cdb-8f92-297bad04490d)

**Comment by techsmyth** [comment]
Really nice work!

Key comments:
- To be generic we probably should rename from Stakeholders to Actors (minor)
- It is important that the "values" are very visually different than the "actors". The actors are what should stand out, they are the key focus, hence the original having them as being a solid bright color and the values being transparent. 
- I would also suggest to not put them beside each other but rather the actors on top and then the values, with the instructions potentially aligned. 

In terms of the sample that is included, it is actors that are shown as nodes in the graph - and then values are attached to the edges between the nodes. And the actors used should come directly from the list of example actors provided. 

Finally, and again a minor point, there should be a "?" block under actors as well as under each type of value. 

Hope the above is clear? Ping me on discord if not...

**Comment by techsmyth** [comment]
My reworking of the canvas at a coarse scale: https://excalidraw.com/#json=2N5p_l-7erf0WDhyYQHZ9,iJDzyGjEnhcfDQq7yfR6Vg

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/2a1ad746-bc59-4608-91e3-9f8637f21104)

**Comment by KayleeS96** [comment]
Link in description has been updated

**Comment by techsmyth** [comment]
Thanks Kaylee. 

One question: when I export from your canvas and then import the contents into a Canvas in Alkemio, I am losing the contents of the icons, any idea why that is?

**Comment by Enderedne** [comment]
Reproduced the issue in an Excalidraw sandbox - seems to be a bug on their side. Will raise an issue on their side.

**Comment by techsmyth** [comment]
v11 of Excallidraw is now released

**Comment by techsmyth** [comment]
Importing nicely now! https://hub.alkem.io/open-innovation/challenges/canvas-templates/canvases
