### ISSUE TITLE
add Github labels

### ISSUE THREAD

**Issue by ReneHonig** [cherrytwist/Coordination#51]
review and update labels (e.g. "off-topic")

**Comment by positivedefinite** [comment]
Would be nice for contributors to see "good first issue" and "help needed" labels. Especially for issues that are about choosing the right software tool for a job.

**Comment by wordsmyth73** [comment]
yes - and was also planning on putting up a project board with those kinds of labels i.e. good issues to start with etc. Open to suggestions...
