### ISSUE TITLE
'Ecoverse' visible when editing a Challenge Hub.

### ISSUE THREAD

**Issue by oldhoyte** [cherrytwist/Coordination#538]
**Describe the bug**
When editing a Challenge Hub as an admin, the word 'Ecoverse' becomes visible. It was mentioned that these should be removed.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/6200e102047aab2b04cbfbce/0bfac9a1-6f69-4ffa-90c3-b24e96748952)

**Comment by hero101** [comment]
This was before the update on hub.alkem.io
Now it's not reproducible.
