### ISSUE TITLE
Spike: Track usage of the platform

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#544]
## Description
As an operator of Alkemio I want to be able to track the usage of the platform

## Acceptance criteria

- [ ] Evaluate a fit-for-purpose usage tracking decision

We are interested in:
- Who are our users (e.g. where are they from)
- Which pages are visited the most / the least
- Engagement per page - how long a user stays on a certain page
Option: look for react component for doing hubspot tracking? 

NOTE: impact on cookie policy?

## Additional Context
The code that typically gets injected looks something like the following:
```
<!-- Start of HubSpot Embed Code -->
<script type="text/javascript" id="hs-script-loader" async defer src="//js-eu1.hs-scripts.com/XXXXX.js"></script>
<!-- End of HubSpot Embed Code -->
```

Note: this has to be configuration of the deployment as the code itself should never go into the open source code base. 
Note2: the person developing this story would need permissions on hubspot

https://www.npmjs.com/package/react-hubspot-tracking-code-hook

**Comment by techsmyth** [comment]
To be reconsidered in light of workshop in Sofia in March

**Comment by hero101** [comment]
## Who are our users (e.g. where are they from)
 Hubspot - https://app-eu1.hubspot.com/analytics/25488729/geolocation
 Sentry - only errors by countries
 
 ## Which pages are visited the most / the least
 Hubspot - https://app-eu1.hubspot.com/analytics/25488729/pages
 Sentry - most visited; longest load times; drill down per route - https://sentry.io/organizations/alkemio/performance/?environment=production&landingDisplay=frontend_other&project=5862875&query=&sort=-count_unique_user&statsPeriod=14d
 
## Engagement per page - how long a user stays on a certain page
 Hubspot - Combination of Page views and Time on page
https://app-eu1.hubspot.com/analytics/25488729/pages?chartType=COMBINATION&compare&endDate=20220526&entireCurrentUnit=false&frequency=WEEK&metric=rawViews&rangeType=ROLLING&rollingDays=60&secondaryMetric=timePerPageview&stacked=true&startDate=20220328

**Comment by valentinyanakiev** [comment]
Discussed with Birgit, Denise, Simone. We'll evaluate hubSpot tracking on demo + hub and whether dashboards are fit-for-purpose.

**Comment by valentinyanakiev** [comment]
Added https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/alkem-io/client-web/2121 as outcome of our discussions
