### ISSUE TITLE
Calendar Events per community

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#555]
## Description
As a community manager, I would like to be able to share with the community upcoming events

## Acceptance criteria

- [ ] Community manager able to add events for a community
- [ ] Events to be displayable in multiple ways / places

**Comment by ccanos** [comment]
A few conclussions from the calls and the Spike: [#3161](https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/gh/alkem-io/client-web/3161)
- The priority is to have a simple list of events + a small calendar view on the Journey pages.
- The database model is going to have: 
   - nameID (to be able to link to a certain event)
   - title
   - description (markdown)
   - createdBy
   - startDate
   - endDate (or duration)
   - fullDay (boolean flag, indicates event lasts the full startDate and ignore the time)
   - location
   - *A comment section*
   - tags?
   - event type?

   We come to the conclusion that events look a lot like cards and that we should consider reusing some functionality

- We confirmed that https://projects.wojtekmaj.pl/react-calendar/ meets the needs, it's nice already but won't take much to tweak styles anyway
- We needed to be able to highlight days and to show a tooltip on the highlighted days and I confirmed that it is possible. 
- We needed to detect clicks on days to be able to add events on clicked days, through a dialog or through a form that appears. That's also possible.
- The agenda view (just a list of the next 3 events for example), will be done manually, it's easy and a custom component will give us the control over what to show and how.
