### ISSUE TITLE
Aspect type label blocking visibility of aspect title; text overlaps

### ISSUE THREAD

**Issue by oldhoyte** [cherrytwist/Coordination#578]
**Describe the bug**
Labels of aspects are blocking the title length. If the label could be moved a bit down, the title could be longer/better visible.

**To Reproduce**
1. Go to 'https://hub.alkem.io/stopthetraffik-ukraine/challenges/poland/contribute'
2. See error

**Screenshots**
![image.png](https://images.zenhubusercontent.com/6200e102047aab2b04cbfbce/ad4f0473-852f-4911-9d8f-196d618d1f4e)

**Expected behavior**
Labels are moved from the current location. UX design pending.

Description text should not overlap with tags.

**Comment by techsmyth** [comment]
Merging with client-web 1878
