### ISSUE TITLE
Translation Management

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#579]
## Description
As a user I want to have up to date translations for all languages
As a product owner I want to be able to manage the translations.

## Acceptance criteria

- [ ] Process + selection of tools for managing translations

**Comment by hero101** [comment]
Findings after a done spike on tool evaluation

## [Locize](https://locize.com/?lng=en)
- [Showcase](https://www.youtube.com/watch?v=ds-yEEYP1Ks)
- [Locize for open source](https://locize.com/open-source.html)
- sync new or removed translation strings (compared with the master language - EN) with a single cli command
- translations are fetched from Locize CDN
- translations can be downloaded
- automatic machine translation is available
- manual machine translation is available
- review workflow - to review translations for a language
- metrics - translated by version, users, health, project metrics, translations used by OS
- auto-generated namespace backups
-  (via plugin) in context editing - the app is opened in an IFRAME in Locize, and by clicking on translatable strings they can be translated on the spot and updated in the translation, and viewed live immediately
- additional descriptions can be attached to strings to improve the translator's experience and accuracy
- (via plugin) find unused translations
- versioning
- attach up to 8 tags to stringsа
- localistars https://www.youtube.com/watch?v=WobsZ_er0I4
- invite translators to the branched project with only the missing keys (crowdbased) - https://www.youtube.com/watch?v=pueV2YSLRfs
- send files through email
- invite new translators 
#### Conclusion
More CDN based without obvious integration to Github, files can be downloaded and used in a build, but additional effort on the infrastructure and scripts is required

## [CrowdIn](https://crowdin.com/)
- [Showcase](https://www.youtube.com/watch?v=7QoHN_qE-OU)
- [Crowdin is completely free of charge for open-source projects](https://crowdin.com/page/open-source-project-setup-request)
- open source license
- file paths need to be configured
- different branches can be configured for sync
- pulls from GitHub on a schedule
- review workflow (called QA)
- creates PR to GitHub on a schedule (can be manual) with a commit per file on a specific crowdin branch (configurable)
- can scan Figma and xd files for strings and transforms them to translatable keys - files can be updated with a new translated screen
- in context translation - overlay over your live website, where you can click on the text and translate it right away
 #### Conclusion
More file based with integration Github and with all if not more features than Locize
