### ISSUE TITLE
Notification Preferences Per entity

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#580]
## Description
As a user I would like to set my notification preferences per entity, not per type

## Acceptance criteria

- [ ] Design for how users are able to set preferences per entity.

**Comment by SimoneZaza** [comment]
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/1650df9f-d4f4-4c62-9e40-5c114fb71f22)

**Comment by SimoneZaza** [comment]
Duplicate (#1054)
