### ISSUE TITLE
UX: Up-to-date Housestyle HackMD

### ISSUE THREAD

**Issue by larssondenise** [cherrytwist/Coordination#586]
## Description
As developer I want a clear document with the ux/ui rules used on the Alkemio website and platform

## Acceptance criteria
- [ ] Updated documentation in alkemio repository, Including
- [ ] colour codes
- [ ] fonts
- [ ] interaction
- [ ] spacing

**Comment by techsmyth** [comment]
This information should actually be as part of the alkemio repository, so version controlled etc.
