### ISSUE TITLE
UX: Up-to-date designs + design components

### ISSUE THREAD

**Issue by larssondenise** [cherrytwist/Coordination#587]
## Description
As a team member I want to quickly be able to make mock-ups for dev
A a team member I want to use up-to-date existing components, so that they are in line with the website/platform for the dev team

## Acceptance criteria
Including
- [ ] all used components
- [ ] mock-ups for each page 
- [ ] easy to use and access

**Comment by Roseghost** [comment]
Adobe with same navigation as this [Example link}
https://xd.adobe.com/view/b213a1ff-f90c-441b-be23-8befbfb355b5-e740/

Gives a speedy navigation through all options and pages.
