### ISSUE TITLE
Data model: Create first representation using an Entity Relationship diagram

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#59]
As an architect, I need to have a full overview of the data model to be able to make integration / design choices + drive alignment.

Acceptance criteria:
- Initial data model available via ERD + reviewed
- Representation available as an independent representation (ER diagram)

**Comment by eruizgar91** [comment]
I created a first graphQL draft with the data that I got from the slides:

**Comment by eruizgar91** [comment]
We can continue editing here:
https://drive.google.com/file/d/1nlnB9uts8nHmfD6rEaINEX-ubkh0-4ft/view?usp=sharing

**Comment by techsmyth** [comment]
To add:
- Work product storage (blobs, links, ...)
- Interactions between users (jediguide app style)
