### ISSUE TITLE
Double email notification about update

### ISSUE THREAD

**Issue by oldhoyte** [cherrytwist/Coordination#614]
**Describe the bug**
When an update is placed in a Hub I'm member of, I receive the notification emails twice. There is a small difference between these emails. Maybe I receive two emails because I'm admin of these hubs?

**Screenshots**
![image.png](https://images.zenhubusercontent.com/6200e102047aab2b04cbfbce/ac6709fe-a3a6-4d51-afc0-8f18e1b9de5e)

![image.png](https://images.zenhubusercontent.com/6200e102047aab2b04cbfbce/e426e969-a839-431f-a8b2-a33b30bbc1de)

**Comment by techsmyth** [comment]
Yes this is you receiving one notification for each role. It is by design. It could be that we make clearer in the email template which notification the email was triggered by?
