### ISSUE TITLE
Migrate UX designs to Figma

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#629]
## Description
As a UX designer I want to have all the designs in one location

## Acceptance criteria

- [ ] All current Components present and working in Figma
- [ ] Current main pages in Figma

## Additional Context

Libraries:

- [ ] Navigation (On hold, due to change of navigation)
- [x] Cards
- [x] Buttons, Input, Icons
- [ ] Search and Filtering
- [x] Pages (Limited to a clean page and the container of components)

**Comment by Roseghost** [comment]
![image.png](https://images.zenhubusercontent.com/612cb1604df0ebe2138b93c9/3b784ba6-8319-475f-8900-c06ed6cf89a8)

Shortlist of whats currently on route and where to find it.
