### ISSUE TITLE
link naar "https://hub.alkem.io/digileefomgeving/challenges/t3d/dashboard" werkt niet meer

### ISSUE THREAD

**Issue by GerlofdeHaan** [cherrytwist/Coordination#635]
De directe link naar https://hub.alkem.io/digileefomgeving/challenges/t3d/dashboard
geeft als resultaat:

![afbeelding](https://user-images.githubusercontent.com/102361398/169837624-4210a602-d853-461c-838a-5a8da521a93a.png)

Dit is het resultaat voor een niet ingelogde gebruiker. Na inloggen opent de betreffende pagina wel.
Een niet ingelogde gebruiker zou in mijn ogen wel moeten "landen" op de beginpagina van de challenge. Vervolgens de mogelijkheid krijgen om een account aan te maken en deel te nemen.

 - Microsoft
 - Firefox
 - Version 100.0.2

**Comment by valentinyanakiev** [comment]
solved with different story
