### ISSUE TITLE
UX: Design for community tab on user profile settings + allowing user to leave

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#681]
## Description
As a user I want to be also able to leave communities

## Acceptance criteria

- [ ] UX design for how users can leave a community. User Profile => Settings ==> Communities
- [ ] UX design for how users can leave a organization. User Profile => Settings ==> Organizations

## Additional Context
Design: https://www.figma.com/file/q32jnaQxiTZhrH67iB8716/Managing-memberships-for-users?node-id=0%3A1

**Comment by techsmyth** [comment]
Good to see this coming together. Key feedback is that a user **leaves** a community, they do not unsubscribe. It could be that they leave certain rights behind etc in the future.

**Comment by SimoneZaza** [comment]
@techsmyth Yes, file is updated

**Comment by yhunink** [comment]
Why you leave me techsmyth?

**Comment by techsmyth** [comment]
good to see you here mr @yhunink  :) At the moment the membership model on communities is a bit too much like hotel california: you can check in any time you like but you can never leave  :)
