### ISSUE TITLE
deleteAspectTemplate mutation throws an error

### ISSUE THREAD

**Issue by me-andre** [cherrytwist/Coordination#685]
**Describe the bug**
Error: "Cannot return null for non-nullable field AspectTemplate.id."

**To Reproduce**
1. Run
```
mutation deleteAspectTemplate($deleteData: DeleteAspectTemplateInput!) {
  deleteAspectTemplate(deleteData: $deleteData) {
    id
    __typename
  }
}
```

**Expected behavior**
The query is able to return the id of the deleted entry.

**Comment by Comoque1** [comment]
The issue was fixed with this [PR](https://github.com/alkem-io/server/pull/2012/files).
Closing this one.
