### ISSUE TITLE
State change impossible to undo?

### ISSUE THREAD

**Issue by yhunink** [cherrytwist/Coordination#688]
**Describe the bug**
I was testing changing the state of a challenge. I can click a button for two options of states, but I cannot go back, or change to a state that is not connected logically. Therefore I cannot undo an action. You end up in the doomed pit of the archive...

**To Reproduce**
1. Go to challenge page as admin, click settings and go to context and scroll down, to see the scheme with buttons for a next state.

**Expected behavior**
You cannot undo your action. And your challenge is forever archived if you persist on clicking.

**Screenshots**
![image](https://user-images.githubusercontent.com/29640880/176526286-ad31f954-6a22-4b83-8a6d-af203ffc8ff5.png)
![image](https://user-images.githubusercontent.com/29640880/176529615-27249a21-374d-4f21-8e26-75a81a268b48.png)

**Desktop (please complete the following information):**
 - OS: [MacOs Catalina 10.15.7]
 - Browser [brave]
 - Version [Version 1.39.120 Chromium: 102.0.5005.99 (Official Build) (x86_64)](https://brave.com/latest/)

**Additional context**
Add any other context about the problem here. It would be nice to adjust the flow of states, because we have a specific proces we use, and sometimes deviating approaches.

**Comment by techsmyth** [comment]
@yhunink yes this is a limitation in the current lifecycle definition that is applied to Challenges. There are two aspects to a solution
- Having more transitions in the state diagram
- Allowing replacing of one lifecycle definition with another

**Comment by techsmyth** [comment]
To be addressed by having more advanced lifecycle templates
