### ISSUE TITLE
Technical analysis for FFE

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#694]
## Description
As a PO I want to understand the effort + complexity in a FFE solution

## Acceptance criteria
- [ ] Brainstorm session including key players to look at the approach
- [ ] MD file with design / considerations for how we could realized a FFE solution

**Comment by hero101** [comment]
What does FFE mean.

**Comment by techsmyth** [comment]
See the linked epic: Focus Front End
