### ISSUE TITLE
UX: Design topbar menu for mobile devices

### ISSUE THREAD

**Issue by ccanos** [cherrytwist/Coordination#710]
## Description

As a user I want to experience the new top level menu on mobile phones
At the moment the top menu is implemented in the PR [#2311](https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/alkem-io/client-web/2311)

![image.png](https://images.zenhubusercontent.com/627279d43b7c526bf418dbb0/0f6f3edf-c6d5-4357-83b0-23f10178dd55)
In small screens buttons don't fit at the top:
![image.png](https://images.zenhubusercontent.com/627279d43b7c526bf418dbb0/edb05865-58f9-455a-a328-2a45619cbdd3)
We can reduce logo size, reduce buttons size, we can create a hamburger menu at the top or do something else. Take into account that there is already a popup menu visible only when the user is logged in:
![image.png](https://images.zenhubusercontent.com/627279d43b7c526bf418dbb0/f740ea0a-6965-4553-a9b6-c192d6ba88ea)

## Acceptance criteria
- [ ] Take a decision about the search bar. At the moment in live, and also for the moment in the new design searchbar is being just removed on small screens, but maybe we want to keep search functionality on mobile phones.
- [ ] figma or xd design of the topbar menu for small screens

Design:
Figma link (updated after session on 19/8): https://www.figma.com/file/0HedEEUFedaC5Irq4Z7sXu/Mobile-Navigation?node-id=0%3A1

**Comment by KayleeS96** [comment]
New design for the mobile navigation as adviced (https://www.figma.com/file/ukGNjMOBuTmlh0zWGMinji/Mobile-Nav?node-id=2%3A2)

If we want to keep the search function, a "hamburger" menu would be adviced, but we can discuss this in a later stage

**Comment by KayleeS96** [comment]
@valentinyanakiev & @techsmyth I have the new version for the mobile navigation. It now has a menu that drops down. In the future we'll have to look at the best way to display the language selector.


![image.png](https://images.zenhubusercontent.com/612cb1848a783db262f19451/20f5e0f9-b680-4252-828c-cf8f71a99c7b)

**Comment by techsmyth** [comment]
Looks much nicer!
