### ISSUE TITLE
Align design / display + refresh of cards for cards / canvas

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#733]
## Description
As a user, I want to see a clean design for the call outs page

## Acceptance criteria

- [ ] UX design for new cards
- [ ] Cards migrated

**Comment by larssondenise** [comment]
Similar to Aspect cards or completely different design? Some differentiation for the user also be desirable?  

![Schermafbeelding 2022-08-10 om 09.35.18.png](https://images.zenhubusercontent.com/6200e10a5561c893d9e84591/8a384334-36b7-4744-b50a-a280d4fe9d06)
