### ISSUE TITLE
UX: Aspect / canvas create flow to align

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#734]
## Description
As a user I want one way of creating new entries

## Acceptance criteria

- [ ] Aspects + canvases to have the same interaction style for creating

## Additional Context
https://www.figma.com/file/olZkcLJKpUYRMjakhfGpB8/Callouts?node-id=0%3A1

**Comment by larssondenise** [comment]
@valentinyanakiev mock-ups for creation + questions added to the Callout figma file!

https://www.figma.com/file/olZkcLJKpUYRMjakhfGpB8/Callouts?node-id=0%3A1

**Comment by larssondenise** [comment]
Updated + comments added
