### ISSUE TITLE
Update 'Challenges' icon

### ISSUE THREAD

**Issue by oldhoyte** [cherrytwist/Coordination#737]
The Challenges icon was not in accordance with what we normally use as a symbol for 'Challenge', namely a mountain. I've picked an icon and sent it through Lazar. Can you replace the current icon (the three diamonds) with the new one?

There are two versions, so maybe see which one fits in best!

![Challenges-icon2.png](https://images.zenhubusercontent.com/6200e102047aab2b04cbfbce/db614b0e-28ad-405a-afd7-8ca986381be0)
![Challenges-icon.png](https://images.zenhubusercontent.com/6200e102047aab2b04cbfbce/a4202e25-d6bc-4580-8a2e-38bc882f0b45)

**Comment by oldhoyte** [comment]
See other issue where icon should be replaced: https://app.zenhub.com/workspaces/alkemio-development-5ecb98b262ebd9f4aec4194c/issues/alkem-io/client-web/2365

**Comment by hero101** [comment]
The changes need to happen inside `TopNavIcons` and to be pushed inside `ux-review` branch.
Contact me for the export svg files from pngs.
