### ISSUE TITLE
Google redirects to wrong page

### ISSUE THREAD

**Issue by oldhoyte** [cherrytwist/Coordination#766]
**Describe the bug**
If you Google a certain page on the Alkemio website (e.g. blogs), you get redirected to the old link, leading you to an empty page on the Hub.

**To Reproduce**
1. Google 'Alkemio blogs'
2. Click on the first link
3. See error

**Expected behavior**
I'd like to be brought to the https://www.alkemio.foundation/post/ 

**Screenshots**
![image.png](https://images.zenhubusercontent.com/6200e102047aab2b04cbfbce/b45f7e98-6361-4cea-bb42-020c640c24e7)

![image.png](https://images.zenhubusercontent.com/6200e102047aab2b04cbfbce/a931527b-ec3b-4a09-969e-fb8a8e3c61a0)

**Comment by techsmyth** [comment]
Google has reindexed to the search results go the right location
