### ISSUE TITLE
Identify development platform + hosting; reference implementation

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#77]
Data Layer
- GraphQL

Storage
- IPFS
- NoSQL / RDMS
(depends on size / responsiveness / etc)

Language options:
- Golang: web3 backend
- Solidity: contracts
(- Python)

Client: web vs mobile
- Flutter?
- Angular?
- React?

Hosting options: 
- AWS
(- Azure)

What are the key platform dependencies? How to isolate?

Needed:
- First pass end-end suggested stack, potentially on AWS Amplify

==> Create a google doc for the technical stack stack

**Comment by aaitor** [comment]
Document added here: https://docs.google.com/document/d/1ju2uQsrL6_nAWCetA0oinc2VOeOECeT9W3KriOLwcJc/edit#
