### ISSUE TITLE
Security model overview updated

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#783]
## Description
As a developer I want an up to date security model document

## Acceptance criteria

- [ ] Detail out the different roles and associated credentials in MD file

**Comment by Comoque1** [comment]
Just a minor comment. 
For global admin role in the example the granted privileges are 
```
{
        type: global-admin,
        resourceID: '',
        authorizations: ['create', 'read', 'update', 'delete'],
        grantedPrivileges: ['create', 'read', 'update', 'delete'],
    }
```

but essentially it has also `Grant` and `Authorization_Reset`
```
{[
      'CREATE',
      'GRANT',
      'READ',
      'UPDATE',
      'DELETE',
      'AUTHORIZATION_RESET',
    ])
````

**Comment by techsmyth** [comment]
it is just an example, so not worth updating it in this documentat - the list will continue to evolve and this document is about explaining the concept, not documenting what exact privileges are assigned
