### ISSUE TITLE
Default discussion callout content for Hub / Challenge

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#790]
## Description
As a user I want a clear way to engage on a Hub / Challenge

## Acceptance criteria

- [ ] Default discussion Callout to be added to Hubs / Challenges

Note: text only, no embedded images

**Comment by larssondenise** [comment]
Ideas 
**Discussions Default Callout Hub**
- Title: Welcome, please introduce yourself to the community!
- Description: You can share a short introduction about yourself. For example, what is your background? What motivates you to work on these Challenges? What brings you to this Hub? Where would you like to contribute? Thank you! 

**Discussions Default Callout Challenge**
- Title: What makes working on this Challenge so difficult?
- Description: We all may share the similar experiences related to this Challenge and together we can make progress. Please share an example of your (personal or work) experiences with us. What is for you the hardest part of working towards solving this challenge? Or what topics do you think this community should focus on to deepen our understanding about this Challenge?

**Comment by larssondenise** [comment]
**Discussions Default Callout Hub**
- Title: Welcome, please introduce yourself to the community!
- Description: We would like to ask you to share a short introduction so that we can get to know the Community and for you to get to know each other! What brings you to this Hub and what motivates you to work on these Challenges? Please share to help make this community

**Discussions Default Callout Challenge**
- Title: ​Why is working on this Challenge so important? 
- Description: Please share an example of your (personal or work) experiences with us. What is for you the main reason for solving this challenge? How will solving this Challenge make a difference for you?

**Comment by techsmyth** [comment]
@larssondenise I think that we need to also add some markdown to the descriptive text so that it stands out a big e.g. bold, some words etc. I also think the text itself needs to be fairly neutral - I would not use "we" as it is not clear who "we" is. Ditto I would not use "us" - so on challenge then more along the lines of "Please share any relevant (personal or work) experience related to this Challenge. What is for you the main reason for solving this challenge? How will solving this Challenge make a difference for you?" etc

**Comment by techsmyth** [comment]
@Fintokyo this is the text that will be seen on the explore page for all Hubs / Challenges - if you have a moment please also feel free to comment...

**Comment by Fintokyo** [comment]
@techsmyth @larssondenise 
My suggestions are:

Discussions Default Callout Hub

Title: Welcome, please introduce yourself to the community!
Description: Please share a few words about yourself to help the community get to know each other. What brings you to this Hub and motivates you to work on these Challenges?

Discussions Default Callout Challenge

Title: ​Why you care about this Challenge!
Description: Please share why this Challenge is important to you and any relevant experience/expertise. 

Some points:
-I assume we are not asking people to 'prove' that they are worthy of joining a challenge, so we're not 'testing' them with our question? I tried to frame it in a way that their sharing of information is purely to help people involved in the challenge to know more about you and how you can and want to help
-I added 'expertise' to 'experience', as some people may not have relevant experience but may have expertise that they can contribute
-Using words that focus on the user ('you') and the challenge and its importance
-In the Callout Challenge, I tried to avoid using the same word 'important' twice
-I think that 'a few words' implies less of a barrier/formality than 'introduction'

Happy to chat on this tomorrow if it helps,
Fintan

**Comment by techsmyth** [comment]
Discussions Default Callout Hub

Title: Welcome, please introduce yourself to the community!
Description: Please share a few words about yourself to help the community get to know each other. What brings you to this Hub and motivates you to work on these Challenges?

Discussions Default Callout Challenge

Title: ​Why do you care about this Challenge?
Description: Please share why this Challenge is important to you as well as any relevant opinions, experience or expertise .

**Comment by Fintokyo** [comment]
Looks good; my only change would be to replace "opinions" with "thoughts". And remove the space before the last full-stop

**Comment by techsmyth** [comment]
thanks, yes that update makes sense! Will use it with the above changes...

**Comment by techsmyth** [comment]
![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/835df162-e292-43e1-8997-c4cfd4187a6f)

and

![image.png](https://images.zenhubusercontent.com/5ecb9817aeb589610134bd43/7126e00f-04a9-400f-a704-6b0582ad4015)
