### ISSUE TITLE
Spike: share icon in navigation bar

### ISSUE THREAD

**Issue by larssondenise** [cherrytwist/Coordination#792]
## Description
As a UX Designer I want a simple design for 

## Acceptance criteria

- [x] Check option to put share icon in navigation bar

**Comment by ccanos** [comment]
![image.png](https://images.zenhubusercontent.com/627279d43b7c526bf418dbb0/d7641c03-b437-4feb-8bb0-1c29e3ad75ed)
![image.png](https://images.zenhubusercontent.com/627279d43b7c526bf418dbb0/f9ad6f64-3573-4901-a629-ff9b584a2156)

Got to have a relatively clean way to add buttons to the NavigationToolbar.
Pushed some code into the branch client-web/spike-792-shareIcon
It's not finished of course, requires some clean up, but the concept is there and the button is working

**Comment by ccanos** [comment]
https://github.com/alkem-io/client-web/tree/spike-792-shareIcon
https://github.com/alkem-io/client-web/compare/develop...spike-792-shareIcon
