### ISSUE TITLE
Leave a community / organization

### ISSUE THREAD

**Issue by larssondenise** [cherrytwist/Coordination#817]
## Description
Currently, Users are able to join a community or organization, but not able to leave it. 

## Initiative / goal
Allow users to leave the community under memberships on their profile

### Hypothesis
Users want to know how they can leave a community or organization

## Acceptance criteria and must have scope
- [ ] Users and organizations able to leave a community
- [ ] Users able to leave an organization
- [ ] Cards refresh

## Additional Context
https://www.figma.com/file/CbYDZUjipUx6dEJR7Dr0H0/Personal-profile-settings?node-id=0%3A1&t=vwxk6TMhUWqTRB7O-1

**Comment by Flor-e** [comment]
To me it would be the most logical solution if the <join> button were to change in a <leave> button once you join somewhere. And yes, I know it involves a bit more than adding a button ;-) Just wouldn't want the unjoin function to be in a different place than where I joined.

**Comment by hero101** [comment]
Have you considered a way to leave from within the page in addition to the membership page?
