### ISSUE TITLE
Bug: visualisation of innovation flow on Safari (Mac)

### ISSUE THREAD

**Issue by oldhoyte** [cherrytwist/Coordination#823]
**Describe the bug**
When creating a Challenge, the visualisation of the innovation flow is wrong. The user used Safari on Mac. Firefox did work. See screenshot below.

**Screenshots**
![image.png](https://images.zenhubusercontent.com/6200e102047aab2b04cbfbce/f2b2fa17-6659-4fac-90f0-21763c00a6d0)

**Comment by techsmyth** [comment]
First we get a proper package for displaying the lifecycle, then we fix it

**Comment by SimoneZaza** [comment]
no longer relevant
