### ISSUE TITLE
UX: create new templates for issues

### ISSUE THREAD

**Issue by larssondenise** [cherrytwist/Coordination#853]
## Description
As a process champion, I want to update the set of templates we use in github

## Acceptance criteria

- [ ] Bug template updated
- [ ] Feature request?

**Comment by SimoneZaza** [comment]
Would be nice to have a design section in the template, eg:
## Design
Figma file: 
_Comments are highly appreciated. When commenting in Figma, please also leave a note in the comments box below this issue to notify us_
