### ISSUE TITLE
Hyperlinks in cards: no new window/tab opened

### ISSUE THREAD

**Issue by oldhoyte** [cherrytwist/Coordination#858]
**Describe the bug**
When clicking on a link in a card, the link gets opened in the same tab. You'd want to open the link in a new tab/window (at least when it links to a page outside of the alkem.io domain). 

This holds for links in the card description and in comments. The references do get opened in a new tab :). 

**To Reproduce**
1. Go to 'https://alkem.io/challengecentric/explore/callouts/inspiringexamples-5547/aspects/dutchopgavegerich-5626/dashboard'
2. Click on the link Hoyte placed in the comments
3. See error

**Comment by techsmyth** [comment]
Please confirm it is related to links in markdown and if so close with a link to the other card.
