### ISSUE TITLE
Assign writer to Callout

### ISSUE THREAD

**Issue by oldhoyte** [cherrytwist/Coordination#868]
**Is your feature request related to a problem? Please describe.**
Users want to see who created a callout. Currently, that's not possible. 

**Describe the solution you'd like**
Therefore it would be nice to show who created the Callout with an avatar. Probably, the data model should be changed where a user is assigned to each Callout that has been created.

**Additional context**
Fast (ugly) mockup I made: 
![image.png](https://images.zenhubusercontent.com/6200e102047aab2b04cbfbce/a3f93320-75e9-42cd-8461-da5c985d20af)

##Design
Figma: https://www.figma.com/file/olZkcLJKpUYRMjakhfGpB8/Callouts?node-id=812%3A1754 (zoom out / in on the version with the box around it)
![image.png](https://images.zenhubusercontent.com/6273938fb2a7cf60e23df935/565c5229-3fdc-4ed0-95ee-7c7cc5eca033)

**Comment by techsmyth** [comment]
@hoyterutteman is the design above, and the write up as in the containing epic what you were thinking off for this?

**Comment by oldhoyte** [comment]
I discussed it with Simone yesterday and yes, I think this is perfect!
