### ISSUE TITLE
Apostrophe error Activity Log

### ISSUE THREAD

**Issue by oldhoyte** [cherrytwist/Coordination#874]
**Describe the bug**
When an apostrophe (') is present in a line of text, the activity log cannot show it properly. Instead, it shows; \&#39;

**Screenshots**
![image.png](https://images.zenhubusercontent.com/6200e102047aab2b04cbfbce/1d60d682-a4aa-4085-8bf4-1a2a90b9fbe2)

**Comment by Comoque1** [comment]
To me it doesn't seem to be [fixed](https://acc.alkem.io/release-13-07-22-hub/dashboard):
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/586b5a0b-3fb4-4f44-af8d-4df6e37ad678)

**Comment by techsmyth** [comment]
The second line per entry is displaying in some cases Markdown e.g. Comment. So the only option is to make that second line a markdown control...

**Comment by me-andre** [comment]
@techsmyth , one problem is that the second line is built using translations. That raw Markdown gets processed by the t() function first and then we have a formatted string can potentially no longer be valid Markdown.

**Comment by Comoque1** [comment]
When it comes to comments in "quots", it looks OK.
The issue with activity description appears, when we have `canvas` or `card` with "quots" in the title.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/46099f68-c138-4663-9430-5ac82c0397ef)

**Comment by techsmyth** [comment]
@me-andre @Comoque1 lets take a short chat on this next week, this needs to be worked out in a discussion...

**Comment by me-andre** [comment]
@techsmyth , I just forgot the entities that have not Markdown-based description. Fixed now.

**Comment by Comoque1** [comment]
Now looks much more better.
Just noticed, that quotes are not shown with their code in the activity title as well.
![image.png](https://images.zenhubusercontent.com/5f5ff9fd50a1a94a1f25f32c/5a0fc909-c74f-4ef9-959d-fb85049cbab3)
