### ISSUE TITLE
Bug: Alkemio logo in login screen

### ISSUE THREAD

**Issue by oldhoyte** [cherrytwist/Coordination#897]
**Describe the bug**
When clicking the Alkemio logo in the login screen, you get redirected to an odd page. 

**To Reproduce**
1. Go to 'https://alkem.io/identity/login?returnUrl=/'
2. Click on 'Alkemio logo'

**Expected behavior**
Go to alkem.io

**Screenshots**
![image.png](https://images.zenhubusercontent.com/6200e102047aab2b04cbfbce/57e0254c-50a7-4aaf-b5df-3bf076ea3bb3)

**Comment by techsmyth** [comment]
To be checked after social login release ready

**Comment by techsmyth** [comment]
Fixed likely with the social login release
