### ISSUE TITLE
Reporting: Additional extensions

### ISSUE THREAD

**Issue by techsmyth** [cherrytwist/Coordination#942]
## Description
We need to understand who is using what funcationality on the platform

## Initiative / goal
Platform management

### Hypothesis
By having visible what funcationity is being used we can better target our capacity

## Acceptance criteria and must have scope
- [ ] What authentication mechanism is being used
- [ ] Platform activity tbd
...

Notes: 
* only logged in users are relevant by definition.
* all hubs regardless of visibility are included (so including Demo hubs)

## Stakeholders
Stewards
DevOps

## Timeline
asap

**Comment by hero101** [comment]
Issued moved to other epics.
